//! Argument modules for each `vs` subcommand.

mod activate;
mod add;
mod available;
mod cd;
mod completion;
mod config;
mod current;
mod exec;
mod hook_env;
mod info;
mod install;
mod list;
mod migrate;
mod remove;
mod resolve;
mod search;
mod uninstall;
mod unuse;
mod update;
mod upgrade;
mod use_tool;
mod version;

pub use activate::ActivateArgs;
pub use add::{AddArgs, BackendArg};
pub use available::AvailableArgs;
pub use cd::CdArgs;
pub use completion::CompletionArgs;
pub use config::ConfigArgs;
pub use current::CurrentArgs;
pub use exec::ExecArgs;
pub use hook_env::HookEnvArgs;
pub use info::InfoArgs;
pub use install::InstallArgs;
pub use list::ListArgs;
pub use migrate::MigrateArgs;
pub use remove::RemoveArgs;
pub use resolve::ResolveArgs;
pub use search::SearchArgs;
pub use uninstall::UninstallArgs;
pub use unuse::UnuseArgs;
pub use update::UpdateArgs;
pub use upgrade::UpgradeArgs;
pub use use_tool::UseArgs;
pub use version::VersionArgs;
